{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-06-02 18:36:46,803\tINFO node.py:469 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-06-02_18-36-46_8156/logs.\n",
      "2019-06-02 18:36:46,944\tINFO services.py:407 -- Waiting for redis server at 127.0.0.1:34624 to respond...\n",
      "2019-06-02 18:36:47,065\tINFO services.py:407 -- Waiting for redis server at 127.0.0.1:20967 to respond...\n",
      "2019-06-02 18:36:47,071\tINFO services.py:804 -- Starting Redis shard with 1.66 GB max memory.\n",
      "2019-06-02 18:36:47,091\tINFO node.py:483 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-06-02_18-36-46_8156/logs.\n",
      "2019-06-02 18:36:47,095\tINFO services.py:1427 -- Starting the Plasma object store with 4.0 GB memory using /dev/shm.\n",
      "2019-06-02 18:36:51,548\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_parquet_columns' with function ID c0b4968ae548eb29942a3720be6d262ba97bd664. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,550\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_parquet_columns' with function ID c0b4968ae548eb29942a3720be6d262ba97bd664. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,550\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_parquet_columns' with function ID c0b4968ae548eb29942a3720be6d262ba97bd664. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,551\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_parquet_columns' with function ID c0b4968ae548eb29942a3720be6d262ba97bd664. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,561\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_csv_with_offset_pandas_on_ray' with function ID 08dd528fa269e2988cbd7ae38c1ee5c8d346c66b. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/generic/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,563\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_csv_with_offset_pandas_on_ray' with function ID 08dd528fa269e2988cbd7ae38c1ee5c8d346c66b. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/generic/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,563\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_csv_with_offset_pandas_on_ray' with function ID 08dd528fa269e2988cbd7ae38c1ee5c8d346c66b. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/generic/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-06-02 18:36:51,564\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_csv_with_offset_pandas_on_ray' with function ID 08dd528fa269e2988cbd7ae38c1ee5c8d346c66b. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/generic/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,565\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_hdf_columns' with function ID 6b59b7f2e1fe6468f28fb0f76561ae0ef9aceddf. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,565\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_hdf_columns' with function ID 6b59b7f2e1fe6468f28fb0f76561ae0ef9aceddf. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,565\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_hdf_columns' with function ID 6b59b7f2e1fe6468f28fb0f76561ae0ef9aceddf. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,566\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_feather_columns' with function ID 3e4ae1160cf93e1dd75af5b9d5aafdcdc35b2566. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,567\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_hdf_columns' with function ID 6b59b7f2e1fe6468f28fb0f76561ae0ef9aceddf. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,567\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_feather_columns' with function ID 3e4ae1160cf93e1dd75af5b9d5aafdcdc35b2566. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-06-02 18:36:51,568\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_sql_with_limit_offset' with function ID 341eddae5984924ce47775ee9ebe16ce431823b3. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,578\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pandas_on_ray.io_exp._read_sql_with_offset_pandas_on_ray' with function ID 543a5d432098f00a3190723b20ffbf26ff416b85. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,579\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_feather_columns' with function ID 3e4ae1160cf93e1dd75af5b9d5aafdcdc35b2566. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,587\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_sql_with_limit_offset' with function ID 341eddae5984924ce47775ee9ebe16ce431823b3. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,588\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_sql_with_limit_offset' with function ID 341eddae5984924ce47775ee9ebe16ce431823b3. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,589\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pandas_on_ray.io_exp._read_sql_with_offset_pandas_on_ray' with function ID 543a5d432098f00a3190723b20ffbf26ff416b85. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,590\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.partition.deploy_ray_func' with function ID d777316c4841b0f618aa7fa0af3806db53356d8c. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-06-02 18:36:51,591\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_feather_columns' with function ID 3e4ae1160cf93e1dd75af5b9d5aafdcdc35b2566. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/io.py\", line 5, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,592\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.partition.deploy_ray_func' with function ID d777316c4841b0f618aa7fa0af3806db53356d8c. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,593\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pandas_on_ray.io_exp._read_sql_with_offset_pandas_on_ray' with function ID 543a5d432098f00a3190723b20ffbf26ff416b85. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,594\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.engines.ray.pandas_on_ray.io._read_sql_with_limit_offset' with function ID 341eddae5984924ce47775ee9ebe16ce431823b3. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,594\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.partition.deploy_ray_func' with function ID d777316c4841b0f618aa7fa0af3806db53356d8c. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,595\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pandas_on_ray.io_exp._read_sql_with_offset_pandas_on_ray' with function ID 543a5d432098f00a3190723b20ffbf26ff416b85. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,596\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.partition.deploy_ray_func' with function ID d777316c4841b0f618aa7fa0af3806db53356d8c. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py\", line 965, in subimport\n",
      "    __import__(name)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-06-02 18:36:51,620\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.axis_partition.deploy_ray_axis_func' with function ID 8244f7f6142069282a6293a91999b29b7a0f8561. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py\", line 5, in <module>\n",
      "    from modin.engines.base.frame.axis_partition import BaseFrameAxisPartition\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/axis_partition.py\", line 1, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,621\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.axis_partition.deploy_ray_axis_func' with function ID 8244f7f6142069282a6293a91999b29b7a0f8561. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py\", line 5, in <module>\n",
      "    from modin.engines.base.frame.axis_partition import BaseFrameAxisPartition\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/axis_partition.py\", line 1, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,622\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.axis_partition.deploy_ray_axis_func' with function ID 8244f7f6142069282a6293a91999b29b7a0f8561. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py\", line 5, in <module>\n",
      "    from modin.engines.base.frame.axis_partition import BaseFrameAxisPartition\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/axis_partition.py\", line 1, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,623\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.axis_partition.deploy_ray_axis_func' with function ID 8244f7f6142069282a6293a91999b29b7a0f8561. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py\", line 5, in <module>\n",
      "    from modin.engines.base.frame.axis_partition import BaseFrameAxisPartition\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/axis_partition.py\", line 1, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,623\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.axis_partition.deploy_ray_func_between_two_axis_partitions' with function ID f5673a60558aff98a36b176c71a5ce53f13d142a. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py\", line 5, in <module>\n",
      "    from modin.engines.base.frame.axis_partition import BaseFrameAxisPartition\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/axis_partition.py\", line 1, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,623\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.axis_partition.deploy_ray_func_between_two_axis_partitions' with function ID f5673a60558aff98a36b176c71a5ce53f13d142a. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py\", line 5, in <module>\n",
      "    from modin.engines.base.frame.axis_partition import BaseFrameAxisPartition\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/axis_partition.py\", line 1, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-06-02 18:36:51,624\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.axis_partition.deploy_ray_func_between_two_axis_partitions' with function ID f5673a60558aff98a36b176c71a5ce53f13d142a. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py\", line 5, in <module>\n",
      "    from modin.engines.base.frame.axis_partition import BaseFrameAxisPartition\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/axis_partition.py\", line 1, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,624\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.frame.axis_partition.deploy_ray_func_between_two_axis_partitions' with function ID f5673a60558aff98a36b176c71a5ce53f13d142a. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py\", line 5, in <module>\n",
      "    from modin.engines.base.frame.axis_partition import BaseFrameAxisPartition\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/axis_partition.py\", line 1, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,635\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.io._read_csv_with_offset_pyarrow_on_ray' with function ID 2f601470d6de2204728b08314a75fe752b9950ac. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/data_management/utils.py\", line 6, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,636\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.io._read_csv_with_offset_pyarrow_on_ray' with function ID 2f601470d6de2204728b08314a75fe752b9950ac. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/data_management/utils.py\", line 6, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,636\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.io._read_csv_with_offset_pyarrow_on_ray' with function ID 2f601470d6de2204728b08314a75fe752b9950ac. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/data_management/utils.py\", line 6, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,647\tERROR worker.py:1672 -- Failed to unpickle the remote function 'modin.experimental.engines.pyarrow_on_ray.io._read_csv_with_offset_pyarrow_on_ray' with function ID 2f601470d6de2204728b08314a75fe752b9950ac. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/function_manager.py\", line 416, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/modin/data_management/utils.py\", line 6, in <module>\n",
      "    import pandas\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,648\tERROR worker.py:1672 -- Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/import_thread.py\", line 132, in fetch_and_execute_function_to_run\n",
      "    function({\"worker\": self.worker})\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 2135, in register_class_for_serialization\n",
      "    \"worker\"].get_serialization_context(driver_id)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 238, in get_serialization_context\n",
      "    _initialize_serialization(driver_id)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 1148, in _initialize_serialization\n",
      "    serialization_context = pyarrow.default_serialization_context()\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 326, in default_serialization_context\n",
      "    register_default_serialization_handlers(context)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 321, in register_default_serialization_handlers\n",
      "    _register_custom_pandas_handlers(serialization_context)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 129, in _register_custom_pandas_handlers\n",
      "    import pandas as pd\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-06-02 18:36:51,648\tERROR worker.py:1672 -- Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/import_thread.py\", line 132, in fetch_and_execute_function_to_run\n",
      "    function({\"worker\": self.worker})\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 2135, in register_class_for_serialization\n",
      "    \"worker\"].get_serialization_context(driver_id)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 238, in get_serialization_context\n",
      "    _initialize_serialization(driver_id)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 1148, in _initialize_serialization\n",
      "    serialization_context = pyarrow.default_serialization_context()\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 326, in default_serialization_context\n",
      "    register_default_serialization_handlers(context)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 321, in register_default_serialization_handlers\n",
      "    _register_custom_pandas_handlers(serialization_context)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 129, in _register_custom_pandas_handlers\n",
      "    import pandas as pd\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,649\tERROR worker.py:1672 -- Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/import_thread.py\", line 132, in fetch_and_execute_function_to_run\n",
      "    function({\"worker\": self.worker})\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 2135, in register_class_for_serialization\n",
      "    \"worker\"].get_serialization_context(driver_id)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 238, in get_serialization_context\n",
      "    _initialize_serialization(driver_id)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 1148, in _initialize_serialization\n",
      "    serialization_context = pyarrow.default_serialization_context()\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 326, in default_serialization_context\n",
      "    register_default_serialization_handlers(context)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 321, in register_default_serialization_handlers\n",
      "    _register_custom_pandas_handlers(serialization_context)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 129, in _register_custom_pandas_handlers\n",
      "    import pandas as pd\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n",
      "2019-06-02 18:36:51,649\tERROR worker.py:1672 -- Traceback (most recent call last):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/import_thread.py\", line 132, in fetch_and_execute_function_to_run\n",
      "    function({\"worker\": self.worker})\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 2135, in register_class_for_serialization\n",
      "    \"worker\"].get_serialization_context(driver_id)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 238, in get_serialization_context\n",
      "    _initialize_serialization(driver_id)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/worker.py\", line 1148, in _initialize_serialization\n",
      "    serialization_context = pyarrow.default_serialization_context()\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 326, in default_serialization_context\n",
      "    register_default_serialization_handlers(context)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 321, in register_default_serialization_handlers\n",
      "    _register_custom_pandas_handlers(serialization_context)\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/ray/pyarrow_files/pyarrow/serialization.py\", line 129, in _register_custom_pandas_handlers\n",
      "    import pandas as pd\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/__init__.py\", line 23, in <module>\n",
      "    from pandas.compat.numpy import *\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/pandas/compat/__init__.py\", line 446, in <module>\n",
      "    import typing\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1356, in <module>\n",
      "    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "  File \"/usr/stud/wangx0/anaconda3/lib/python3.7/site-packages/typing.py\", line 1004, in __new__\n",
      "    self._abc_registry = extra._abc_registry\n",
      "AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import modin.pandas as pd\n",
    "import numpy as np\n",
    "import os\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# base_path = r'D:\\TUM论文工作\\第五周工作\\数据\\数据5'\n",
    "# base_path = r'/usr/stud/wangx0/storage/slurm/JieW/highd1/tracksenrich'\n",
    "# files = os.listdir(base_path)\n",
    "# files.sort(key=lambda x: int(x.split('_')[0]))\n",
    "# dfs1=[]\n",
    "# for path in files:\n",
    "#     full_path = os.path.join(base_path, path)\n",
    "#     dfs1.append(pd.read_csv(full_path))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def drivingscenereproduce(df):\n",
    "    for i in range(df1.shape[0]):\n",
    "        a=df1.at[i,'frame']\n",
    "        b1=df1.at[i,'precedingId']\n",
    "        b2=df1.at[i,'followingId']\n",
    "        b3=df1.at[i,'leftPrecedingId']\n",
    "        b4=df1.at[i,'leftAlongsideId']\n",
    "        b5=df1.at[i, 'leftFollowingId']\n",
    "        b6=df1.at[i, 'rightPrecedingId']\n",
    "        b7=df1.at[i,'rightAlongsideId']\n",
    "        b8=df1.at[i, 'rightFollowingId']\n",
    "        if b1==0:\n",
    "            pass\n",
    "            #df1.at[i,['prex','prey','prexVelocity','preyVelocity','prexAcceleration','preyAcceleration']=0\n",
    "        else:\n",
    "            df2=df1.loc[(df1['frame'] == a) & (df1['id'] == b1)]\n",
    "            df2.index=[1]\n",
    "            df1.at[i,'prex']=df2.at[1,'x']\n",
    "            df1.at[i,'prey']=df2.at[1,'y']\n",
    "            df1.at[i,'prexVelocity']=df2.at[1,'xVelocity']\n",
    "            df1.at[i,'preyVelocity']=df2.at[1,'yVelocity']\n",
    "            df1.at[i,'prexAcceleration']=df2.at[1,'xAcceleration']\n",
    "            df1.at[i,'preyAcceleration']=df2.at[1,'yAcceleration']\n",
    "        if b2==0:\n",
    "            pass\n",
    "            #df1.at[i,['prex','prey','prexVelocity','preyVelocity','prexAcceleration','preyAcceleration']=0\n",
    "        else:\n",
    "            df2=df1.loc[(df1['frame'] == a) & (df1['id'] == b2)]\n",
    "            df2.index=[1]\n",
    "            df1.at[i,'folx']=df2.at[1,'x']\n",
    "            df1.at[i,'foly']=df2.at[1,'y']\n",
    "            df1.at[i,'folxVelocity']=df2.at[1,'xVelocity']\n",
    "            df1.at[i,'folyVelocity']=df2.at[1,'yVelocity']\n",
    "            df1.at[i,'folxAcceleration']=df2.at[1,'xAcceleration']\n",
    "            df1.at[i,'folyAcceleration']=df2.at[1,'yAcceleration']   \n",
    "        if b3==0:\n",
    "            pass\n",
    "            #df1.at[i,['prex','prey','prexVelocity','preyVelocity','prexAcceleration','preyAcceleration']=0\n",
    "        else:\n",
    "            df2=df1.loc[(df1['frame'] == a) & (df1['id'] == b3)]\n",
    "            df2.index=[1]\n",
    "            df1.at[i,'lprx']=df2.at[1,'x']\n",
    "            df1.at[i,'lpry']=df2.at[1,'y']\n",
    "            df1.at[i,'lprxVelocity']=df2.at[1,'xVelocity']\n",
    "            df1.at[i,'lpryVelocity']=df2.at[1,'yVelocity']\n",
    "            df1.at[i,'lprxAcceleration']=df2.at[1,'xAcceleration']\n",
    "            df1.at[i,'lpryAcceleration']=df2.at[1,'yAcceleration']  \n",
    "        if b4==0:\n",
    "            pass\n",
    "            #df1.at[i,['prex','prey','prexVelocity','preyVelocity','prexAcceleration','preyAcceleration']=0\n",
    "        else:\n",
    "            df2=df1.loc[(df1['frame'] == a) & (df1['id'] == b4)]\n",
    "            df2.index=[1]\n",
    "            df1.at[i,'lalx']=df2.at[1,'x']\n",
    "            df1.at[i,'laly']=df2.at[1,'y']\n",
    "            df1.at[i,'lalxVelocity']=df2.at[1,'xVelocity']\n",
    "            df1.at[i,'lalyVelocity']=df2.at[1,'yVelocity']\n",
    "            df1.at[i,'lalxAcceleration']=df2.at[1,'xAcceleration']\n",
    "            df1.at[i,'lalyAcceleration']=df2.at[1,'yAcceleration']   \n",
    "        if b5==0:\n",
    "            pass\n",
    "            #df1.at[i,['prex','prey','prexVelocity','preyVelocity','prexAcceleration','preyAcceleration']=0\n",
    "        else:\n",
    "            df2=df1.loc[(df1['frame'] == a) & (df1['id'] == b5)]\n",
    "            df2.index=[1]\n",
    "            df1.at[i,'lfox']=df2.at[1,'x']\n",
    "            df1.at[i,'lfoy']=df2.at[1,'y']\n",
    "            df1.at[i,'lfoxVelocity']=df2.at[1,'xVelocity']\n",
    "            df1.at[i,'lfoyVelocity']=df2.at[1,'yVelocity']\n",
    "            df1.at[i,'lfoxAcceleration']=df2.at[1,'xAcceleration']\n",
    "            df1.at[i,'lfoyAcceleration']=df2.at[1,'yAcceleration']   \n",
    "        if b6==0:\n",
    "            pass\n",
    "            #df1.at[i,['prex','prey','prexVelocity','preyVelocity','prexAcceleration','preyAcceleration']=0\n",
    "        else:\n",
    "            df2=df1.loc[(df1['frame'] == a) & (df1['id'] == b6)]\n",
    "            df2.index=[1]\n",
    "            df1.at[i,'rprx']=df2.at[1,'x']\n",
    "            df1.at[i,'rpry']=df2.at[1,'y']\n",
    "            df1.at[i,'rprxVelocity']=df2.at[1,'xVelocity']\n",
    "            df1.at[i,'rpryVelocity']=df2.at[1,'yVelocity']\n",
    "            df1.at[i,'rprxAcceleration']=df2.at[1,'xAcceleration']\n",
    "            df1.at[i,'rpryAcceleration']=df2.at[1,'yAcceleration']\n",
    "        if b7==0:\n",
    "            pass\n",
    "            #df1.at[i,['prex','prey','prexVelocity','preyVelocity','prexAcceleration','preyAcceleration']=0\n",
    "        else:\n",
    "            df2=df1.loc[(df1['frame'] == a) & (df1['id'] == b7)]\n",
    "            df2.index=[1]\n",
    "            df1.at[i,'ralx']=df2.at[1,'x']\n",
    "            df1.at[i,'raly']=df2.at[1,'y']\n",
    "            df1.at[i,'ralxVelocity']=df2.at[1,'xVelocity']\n",
    "            df1.at[i,'ralyVelocity']=df2.at[1,'yVelocity']\n",
    "            df1.at[i,'ralxAcceleration']=df2.at[1,'xAcceleration']\n",
    "            df1.at[i,'ralyAcceleration']=df2.at[1,'yAcceleration']\n",
    "        if b8==0:\n",
    "            pass\n",
    "            #df1.at[i,['prex','prey','prexVelocity','preyVelocity','prexAcceleration','preyAcceleration']=0\n",
    "        else:\n",
    "            df2=df1.loc[(df1['frame'] == a) & (df1['id'] == b8)]\n",
    "            df2.index=[1]\n",
    "            df1.at[i,'rfox']=df2.at[1,'x']\n",
    "            df1.at[i,'rfoy']=df2.at[1,'y']\n",
    "            df1.at[i,'rfoxVelocity']=df2.at[1,'xVelocity']\n",
    "            df1.at[i,'rfoyVelocity']=df2.at[1,'yVelocity']\n",
    "            df1.at[i,'rfoxAcceleration']=df2.at[1,'xAcceleration']\n",
    "            df1.at[i,'rfoyAcceleration']=df2.at[1,'yAcceleration']\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "base_path = r'/usr/stud/wangx0/storage/slurm/JieW/highd1/tracksenrich'\n",
    "files = os.listdir(base_path)\n",
    "files.sort(key=lambda x: int(x.split('_')[0]))\n",
    "for path in files:\n",
    "    i=0\n",
    "    t1=time.time()\n",
    "    full_path = os.path.join(base_path, path)\n",
    "    df1=pd.read_csv(full_path)\n",
    "    del df1['Unnamed: 0']\n",
    "    drivingscenereproduce(df1)\n",
    "    df1.to_csv(r'/usr/stud/wangx0/storage/slurm/JieW/highd1/scenario/%d_trackscene.csv'%(i+1))\n",
    "    t2=time.time()\n",
    "    i=i+1\n",
    "    print('%d_process time:'%(i+1))\n",
    "    print(t2-t1)\n",
    "    break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# #a=[10]\n",
    "# num_data=60\n",
    "# for i in range(num_data):\n",
    "#     t1=time.time()\n",
    "#     df1=dfs1[i]\n",
    "#     del df1['Unnamed: 0']\n",
    "#     drivingscenereproduce(df1)\n",
    "#     df1.to_csv(r'/usr/stud/wangx0/storage/slurm/JieW/highd1/scenario/%d_trackscene.csv'%(i+1))\n",
    "#     t2=time.time()\n",
    "#     print('%d_process time:'%(i+1))\n",
    "#     print(t2-t1)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
